[package]
name = "remote"
version = "0.1.0"

[dependencies]
http = "0.2"
libc = "0.2"
log = "0.4"
nserror = { path = "../../../xpcom/rust/nserror" }
nsstring = { path = "../../../xpcom/rust/nsstring" }
thiserror = "1"
xpcom = { path = "../../../xpcom/rust/xpcom" }
