[css-masonry]
title = "experimental-features-css-masonry"
description = "experimental-features-css-masonry-description"
description-links = {explainer = "https://github.com/w3c/csswg-drafts/blob/master/css-grid-2/MASONRY-EXPLAINER.md", w3c-issue = "https://github.com/w3c/csswg-drafts/issues/4650", bug = "https://bugzilla.mozilla.org/show_bug.cgi?id=1607439"}
restart-required = false
preference = "layout.css.grid-template-masonry-value.enabled"
type = "boolean"
bug-numbers = [1607954]
is-public = true
default-value = false

[web-gpu]
title = "experimental-features-web-gpu"
description = "experimental-features-web-gpu-description"
restart-required = true
preference = "dom.webgpu.enabled"
type = "boolean"
bug-numbers = [1602129]
is-public = {default = false, nightly = true}
default-value = false

[avif]
title = "experimental-features-avif"
description = "experimental-features-avif-description"
restart-required = false
preference = "image.avif.enabled"
type = "boolean"
bug-numbers = [1443863]
is-public = {default = false, nightly = true}
default-value = false

[cookie-samesite-lax-by-default]
title = "experimental-features-cookie-samesite-lax-by-default2"
description = "experimental-features-cookie-samesite-lax-by-default2-description"
restart-required = false
preference = "network.cookie.sameSite.laxByDefault"
type = "boolean"
bug-numbers = [1618610]
default-value = {default = false, nightly = true}
is-public = true

[cookie-samesite-none-requires-secure]
title = "experimental-features-cookie-samesite-none-requires-secure2"
description = "experimental-features-cookie-samesite-none-requires-secure2-description"
restart-required = false
preference = "network.cookie.sameSite.noneRequiresSecure"
type = "boolean"
bug-numbers = [1618610]
is-public = true
default-value = {default = false, nightly = true}

[abouthome-startup-cache]
title = "experimental-features-abouthome-startup-cache"
description = "experimental-features-abouthome-startup-cache-description"
restart-required = true
preference = "browser.startup.homepage.abouthome_cache.enabled"
type = "boolean"
bug-numbers = [1614351]
is-public = true
default-value = false

[cookie-samesite-schemeful]
title = "experimental-features-cookie-samesite-schemeful"
description = "experimental-features-cookie-samesite-schemeful-description"
restart-required = false
preference = "network.cookie.sameSite.schemeful"
type = "boolean"
bug-numbers = [1651119]
is-public = true
default-value = {default = false, nightly = true}

[serviceworker-debugger-support]
title = "experimental-features-serviceworker-debugger-support"
description = "experimental-features-serviceworker-debugger-support-description"
restart-required = true
preference = "devtools.debugger.features.windowless-service-workers"
type = "boolean"
bug-numbers = [1651607]
is-public = true
default-value = false
